
/* Root required
CREATE DATABASE RUGBY_APP;
GRANT ALL PRIVILEGES ON RUGBY_APP.* TO 'test'@'localhost';
*/

CREATE TABLE FAN (
    ID INT NOT NULL AUTO_INCREMENT, 
    NOME VARCHAR(100) NOT NULL,
    DOCUMENTO VARCHAR(15),
    CEP VARCHAR(10),
    ENDERECO VARCHAR(200),
    BAIRRO VARCHAR(100),
    CIDADE VARCHAR(70),
    UF VARCHAR(2),
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(50),
    ATIVO VARCHAR(3),
    /* not for now; require more logic to be written */
    /*UNIQUE(DOCUMENTO), */
    PRIMARY KEY(ID)
);

ALTER TABLE FAN ADD COLUMN updated_at DATETIME;
ALTER TABLE FAN ADD COLUMN created_at DATETIME;
